/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThoughtcastsRouteImport } from './routes/thoughtcasts'
import { Route as TellYourStoryRouteImport } from './routes/tell-your-story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as MustardSeedRouteImport } from './routes/mustard-seed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThoughtcastsSlugRouteImport } from './routes/thoughtcasts.$slug'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'

const ThoughtcastsRoute = ThoughtcastsRouteImport.update({
  id: '/thoughtcasts',
  path: '/thoughtcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const TellYourStoryRoute = TellYourStoryRouteImport.update({
  id: '/tell-your-story',
  path: '/tell-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const MustardSeedRoute = MustardSeedRouteImport.update({
  id: '/mustard-seed',
  path: '/mustard-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtcastsSlugRoute = ThoughtcastsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThoughtcastsRoute,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PodcastRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mustard-seed': typeof MustardSeedRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/thoughtcasts': typeof ThoughtcastsRouteWithChildren
  '/podcast/$slug': typeof PodcastSlugRoute
  '/thoughtcasts/$slug': typeof ThoughtcastsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mustard-seed': typeof MustardSeedRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/thoughtcasts': typeof ThoughtcastsRouteWithChildren
  '/podcast/$slug': typeof PodcastSlugRoute
  '/thoughtcasts/$slug': typeof ThoughtcastsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mustard-seed': typeof MustardSeedRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/thoughtcasts': typeof ThoughtcastsRouteWithChildren
  '/podcast/$slug': typeof PodcastSlugRoute
  '/thoughtcasts/$slug': typeof ThoughtcastsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mustard-seed'
    | '/podcast'
    | '/sitemap.xml'
    | '/tell-your-story'
    | '/thoughtcasts'
    | '/podcast/$slug'
    | '/thoughtcasts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mustard-seed'
    | '/podcast'
    | '/sitemap.xml'
    | '/tell-your-story'
    | '/thoughtcasts'
    | '/podcast/$slug'
    | '/thoughtcasts/$slug'
  id:
    | '__root__'
    | '/'
    | '/mustard-seed'
    | '/podcast'
    | '/sitemap.xml'
    | '/tell-your-story'
    | '/thoughtcasts'
    | '/podcast/$slug'
    | '/thoughtcasts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MustardSeedRoute: typeof MustardSeedRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TellYourStoryRoute: typeof TellYourStoryRoute
  ThoughtcastsRoute: typeof ThoughtcastsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thoughtcasts': {
      id: '/thoughtcasts'
      path: '/thoughtcasts'
      fullPath: '/thoughtcasts'
      preLoaderRoute: typeof ThoughtcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tell-your-story': {
      id: '/tell-your-story'
      path: '/tell-your-story'
      fullPath: '/tell-your-story'
      preLoaderRoute: typeof TellYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mustard-seed': {
      id: '/mustard-seed'
      path: '/mustard-seed'
      fullPath: '/mustard-seed'
      preLoaderRoute: typeof MustardSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughtcasts/$slug': {
      id: '/thoughtcasts/$slug'
      path: '/$slug'
      fullPath: '/thoughtcasts/$slug'
      preLoaderRoute: typeof ThoughtcastsSlugRouteImport
      parentRoute: typeof ThoughtcastsRoute
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof PodcastRoute
    }
  }
}

interface PodcastRouteChildren {
  PodcastSlugRoute: typeof PodcastSlugRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastSlugRoute: PodcastSlugRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

interface ThoughtcastsRouteChildren {
  ThoughtcastsSlugRoute: typeof ThoughtcastsSlugRoute
}

const ThoughtcastsRouteChildren: ThoughtcastsRouteChildren = {
  ThoughtcastsSlugRoute: ThoughtcastsSlugRoute,
}

const ThoughtcastsRouteWithChildren = ThoughtcastsRoute._addFileChildren(
  ThoughtcastsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MustardSeedRoute: MustardSeedRoute,
  PodcastRoute: PodcastRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TellYourStoryRoute: TellYourStoryRoute,
  ThoughtcastsRoute: ThoughtcastsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
