/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThoughtcastsRouteImport } from './routes/thoughtcasts'
import { Route as TellYourStoryRouteImport } from './routes/tell-your-story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentCanceledRouteImport } from './routes/payment-canceled'
import { Route as MustardSeedRouteImport } from './routes/mustard-seed'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThoughtcastsSlugRouteImport } from './routes/thoughtcasts.$slug'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as PodcastSlugRouteImport } from './routes/podcast.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminGuestsIdRouteImport } from './routes/_authenticated.admin.guests.$id'
import { Route as AuthenticatedAdminEpisodesIdRouteImport } from './routes/_authenticated.admin.episodes.$id'

const ThoughtcastsRoute = ThoughtcastsRouteImport.update({
  id: '/thoughtcasts',
  path: '/thoughtcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const TellYourStoryRoute = TellYourStoryRouteImport.update({
  id: '/tell-your-story',
  path: '/tell-your-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCanceledRoute = PaymentCanceledRouteImport.update({
  id: '/payment-canceled',
  path: '/payment-canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const MustardSeedRoute = MustardSeedRouteImport.update({
  id: '/mustard-seed',
  path: '/mustard-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtcastsSlugRoute = ThoughtcastsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThoughtcastsRoute,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastSlugRoute = PodcastSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PodcastRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminGuestsIdRoute =
  AuthenticatedAdminGuestsIdRouteImport.update({
    id: '/guests/$id',
    path: '/guests/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEpisodesIdRoute =
  AuthenticatedAdminEpisodesIdRouteImport.update({
    id: '/episodes/$id',
    path: '/episodes/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/mustard-seed': typeof MustardSeedRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/thoughtcasts': typeof ThoughtcastsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/podcast/$slug': typeof PodcastSlugRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/thoughtcasts/$slug': typeof ThoughtcastsSlugRoute
  '/admin/episodes/$id': typeof AuthenticatedAdminEpisodesIdRoute
  '/admin/guests/$id': typeof AuthenticatedAdminGuestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/mustard-seed': typeof MustardSeedRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/thoughtcasts': typeof ThoughtcastsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/podcast/$slug': typeof PodcastSlugRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/thoughtcasts/$slug': typeof ThoughtcastsSlugRoute
  '/admin/episodes/$id': typeof AuthenticatedAdminEpisodesIdRoute
  '/admin/guests/$id': typeof AuthenticatedAdminGuestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/donate': typeof DonateRoute
  '/mustard-seed': typeof MustardSeedRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tell-your-story': typeof TellYourStoryRoute
  '/thoughtcasts': typeof ThoughtcastsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/podcast/$slug': typeof PodcastSlugRoute
  '/preview/$token': typeof PreviewTokenRoute
  '/thoughtcasts/$slug': typeof ThoughtcastsSlugRoute
  '/_authenticated/admin/episodes/$id': typeof AuthenticatedAdminEpisodesIdRoute
  '/_authenticated/admin/guests/$id': typeof AuthenticatedAdminGuestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/donate'
    | '/mustard-seed'
    | '/payment-canceled'
    | '/payment-success'
    | '/podcast'
    | '/sitemap.xml'
    | '/tell-your-story'
    | '/thoughtcasts'
    | '/admin'
    | '/podcast/$slug'
    | '/preview/$token'
    | '/thoughtcasts/$slug'
    | '/admin/episodes/$id'
    | '/admin/guests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/donate'
    | '/mustard-seed'
    | '/payment-canceled'
    | '/payment-success'
    | '/podcast'
    | '/sitemap.xml'
    | '/tell-your-story'
    | '/thoughtcasts'
    | '/admin'
    | '/podcast/$slug'
    | '/preview/$token'
    | '/thoughtcasts/$slug'
    | '/admin/episodes/$id'
    | '/admin/guests/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/donate'
    | '/mustard-seed'
    | '/payment-canceled'
    | '/payment-success'
    | '/podcast'
    | '/sitemap.xml'
    | '/tell-your-story'
    | '/thoughtcasts'
    | '/_authenticated/admin'
    | '/podcast/$slug'
    | '/preview/$token'
    | '/thoughtcasts/$slug'
    | '/_authenticated/admin/episodes/$id'
    | '/_authenticated/admin/guests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DonateRoute: typeof DonateRoute
  MustardSeedRoute: typeof MustardSeedRoute
  PaymentCanceledRoute: typeof PaymentCanceledRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TellYourStoryRoute: typeof TellYourStoryRoute
  ThoughtcastsRoute: typeof ThoughtcastsRouteWithChildren
  PreviewTokenRoute: typeof PreviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thoughtcasts': {
      id: '/thoughtcasts'
      path: '/thoughtcasts'
      fullPath: '/thoughtcasts'
      preLoaderRoute: typeof ThoughtcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tell-your-story': {
      id: '/tell-your-story'
      path: '/tell-your-story'
      fullPath: '/tell-your-story'
      preLoaderRoute: typeof TellYourStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-canceled': {
      id: '/payment-canceled'
      path: '/payment-canceled'
      fullPath: '/payment-canceled'
      preLoaderRoute: typeof PaymentCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mustard-seed': {
      id: '/mustard-seed'
      path: '/mustard-seed'
      fullPath: '/mustard-seed'
      preLoaderRoute: typeof MustardSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughtcasts/$slug': {
      id: '/thoughtcasts/$slug'
      path: '/$slug'
      fullPath: '/thoughtcasts/$slug'
      preLoaderRoute: typeof ThoughtcastsSlugRouteImport
      parentRoute: typeof ThoughtcastsRoute
    }
    '/preview/$token': {
      id: '/preview/$token'
      path: '/preview/$token'
      fullPath: '/preview/$token'
      preLoaderRoute: typeof PreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$slug': {
      id: '/podcast/$slug'
      path: '/$slug'
      fullPath: '/podcast/$slug'
      preLoaderRoute: typeof PodcastSlugRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/guests/$id': {
      id: '/_authenticated/admin/guests/$id'
      path: '/guests/$id'
      fullPath: '/admin/guests/$id'
      preLoaderRoute: typeof AuthenticatedAdminGuestsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/episodes/$id': {
      id: '/_authenticated/admin/episodes/$id'
      path: '/episodes/$id'
      fullPath: '/admin/episodes/$id'
      preLoaderRoute: typeof AuthenticatedAdminEpisodesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEpisodesIdRoute: typeof AuthenticatedAdminEpisodesIdRoute
  AuthenticatedAdminGuestsIdRoute: typeof AuthenticatedAdminGuestsIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEpisodesIdRoute: AuthenticatedAdminEpisodesIdRoute,
  AuthenticatedAdminGuestsIdRoute: AuthenticatedAdminGuestsIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PodcastRouteChildren {
  PodcastSlugRoute: typeof PodcastSlugRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastSlugRoute: PodcastSlugRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

interface ThoughtcastsRouteChildren {
  ThoughtcastsSlugRoute: typeof ThoughtcastsSlugRoute
}

const ThoughtcastsRouteChildren: ThoughtcastsRouteChildren = {
  ThoughtcastsSlugRoute: ThoughtcastsSlugRoute,
}

const ThoughtcastsRouteWithChildren = ThoughtcastsRoute._addFileChildren(
  ThoughtcastsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DonateRoute: DonateRoute,
  MustardSeedRoute: MustardSeedRoute,
  PaymentCanceledRoute: PaymentCanceledRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PodcastRoute: PodcastRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TellYourStoryRoute: TellYourStoryRoute,
  ThoughtcastsRoute: ThoughtcastsRouteWithChildren,
  PreviewTokenRoute: PreviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
